version: "3.7"
services:
    db:
        image: postgres
        container_name: postgres
        networks:
            - webnet
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5434:5432"
    web:
        build: .
        depends_on:
            - db
        ports:
            - "${PORT}:3000"
        networks:
            - webnet
        environment:
            DB_HOST: db
            PORT: 3000
            DATABASE_URL: ${DATABASE_URL}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_USER: ${DB_USER}
            DB_NAME: ${DB_NAME}
        command: [
                # "apk",
                # "add",
                # "--no-cache",
                # "bash",
                # "sh",
                # "./wait-for-it.sh",
                # "db:5434",
                # "-t:0",
                # "--",
                "npm",
                "run",
                "start",
            ]
networks:
    webnet:
volumes:
    pgdata:
    static_volume:
