version: "3.7"
services:
    db:
        image: postgres
        container_name: postgres
        networks:
            - webnet
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5434:5432"
    web:
        image: tolumide/modelling
        depends_on:
            - db
        ports:
            - 4000:3000
        networks:
            - webnet
        environment:
            # DB_HOST: db
            DB_HOST: ${DB_HOST}
            PORT: 3000
            DATABASE_URL: ${DATABASE_URL}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_USERNAME: ${DB_USERNAME}
            DB_DATABASE: ${DB_DATABASE}
            AMAZON_S3_BUCKET: ${AMAZON_S3_BUCKET}
            AMAZON_S3_SECRET_KEY: ${AMAZON_S3_SECRET_KEY}
            AMAZON_S3_ACCESS_KEY: ${AMAZON_S3_ACCESS_KEY}
            # DB_PORT: 5432
            DB_PORT: ${DB_PORT}
            NODE_ENV: development
        entrypoint: ["/bin/bash", "./entrypoint.sh"]

networks:
    webnet:
volumes:
    pgdata:
    static_volume:
